### ISSUE TITLE
Get rid of `publish-travis.sh`

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2570]
The bash script is getting unmanageable. 
Instead we can define travis jobs explicitly in a clearer jobs spec, here is a simplified example. 

```yml

scala: 
    - 2.11.12
    - 2.12.6
    - 2.13.0-M4
jobs:
  include:
    - env:
        - NAME="Validate JVM"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION validateJVM

    - if: env(TRAVIS_SCALA_VERSION) =~ /^2.12/ 
      env:
        - NAME="Validate docs"
      script:
        - sbt docs/tut

    - if: (branch = master) AND (type = pull_request)
      env:
        - NAME="Publish SNAPSHOT"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION publish gitSnapshots publish

```
